application: is-it-live
version: 1
runtime: python27
api_version: 1
threadsafe: yes

resources:
  cpu: .5
  memory_gb: 1.3

handlers:
- url: .*
  script: app.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: ssl
  version: latest
